FROM python:3.11-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libsndfile1 \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# Work dir setup
WORKDIR /workspace

# Install requirements
COPY backend/requirements.txt requirements.txt
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Copy backend files and root core
COPY backend /workspace/backend
COPY backend/core /workspace/core

EXPOSE 8001

# Start Trainer server
CMD ["uvicorn", "backend.app.main_trainer:app", "--host", "0.0.0.0", "--port", "8001"]
